version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/php #valid path where code has to be updated.
file_exists_behavior: OVERWRITE #this will overwrite all the existing files. 

permissions:
  - object: /home/ubuntu/php/
    pattern: "**"
    owner: ubuntu
    mode: 777
    type:
      - file
hooks:
  AfterInstall:
    - location: ./Dependency_Scripts/startApplication.sh
      timeout: 350
      runas: ubuntu
