version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html #valid path where code has to be updated.
file_exists_behavior: OVERWRITE #this will overwrite all the existing files. 

hooks:
  ApplicationStart:
    - location: Dependency_Scripts/startApplication.sh
      timeout: 300
      runas: ubuntu
